auth/urls.py
from django.urls import path

from auth.views import (
    GitHubAuthRedirectView,
    GitHubAuthView,
    RegistrationView,
)

app_name = 'auth'
urlpatterns = [
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('github/', GitHubAuthRedirectView.as_view(), name='github'),
    path('github/login/', GitHubAuthView.as_view(), name='github-login'),
]

config/urls.py
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from contributors.admin.custom import site
from contributors.sitemap import sitemaps
from contributors.views import robots


def trigger_error(request):
    """Trigger error for Sentry checking."""
    division_by_zero = 1 / 0  # noqa: F841


urlpatterns = [
    path('admin/', site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript_catalog'),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/', include('auth.urls')),
    path('', include('contributors.urls')),
    path('sentry-debug/', trigger_error),
    path('robots.txt', robots.RobotsTxtView.as_view(), name='robots_txt'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

contributors/urls.py
from django.urls import path

from contributors import views

app_name = 'contributors'
urlpatterns = [
    path('', views.home.HomeView.as_view(), name='home'),
    path(
        '<slug:slug>/settings/account/edit',
        views.user_settings.ChangeTokenView.as_view(),
        name='user_settings',
    ),
    path(
        'organizations/',
        views.organizations.ListView.as_view(),
        name='organizations_list',
    ),
    path(
        'organizations/<slug:slug>',
        views.organization.OrgRepositoryList.as_view(),
        name='organization_details',
    ),
    path(
        'repositories/',
        views.repositories.ListView.as_view(),
        name='repositories_list',
    ),
    path(
        'repositories/<path:slug>',
        views.repository.RepoContributorList.as_view(),
        name='repository_details',
    ),
    path(
        'leaderboard/commits',
        views.leaderboards.CommitsListView.as_view(),
        name='leaderboard_commits',
    ),
    path(
        'leaderboard/pull-requests',
        views.leaderboards.PrsListView.as_view(),
        name='leaderboard_prs',
    ),
    path(
        'leaderboard/issues',
        views.leaderboards.IssuesListView.as_view(),
        name='leaderboard_issues',
    ),
    path(
        'contributors/',
        views.contributors.ListView.as_view(),
        name='contributors_list',
    ),
    path(
        'contributors/for-month',
        views.contributors_for_period.ListView.as_view(
            extra_context={'period': 'month'},
        ),
        name='contributors_for_month',
    ),
    path(
        'contributors/for-week',
        views.contributors_for_period.ListView.as_view(
            extra_context={'period': 'week'},
        ),
        name='contributors_for_week',
    ),
    path(
        'contributors/<slug:slug>',
        views.contributor.DetailView.as_view(),
        name='contributor_details',
    ),
    path(
        'contributors/<slug:slug>/issues/',
        views.contributor_issues.ListView.as_view(),
        name='contributor_issues',
    ),
    path(
        'contributors/<slug:slug>/pullrequests/',
        views.contributor_prs.ListView.as_view(),
        name='contributor_pullrequests',
    ),
    path(
        'projects/',
        views.projects.ListView.as_view(),
        name='projects_list',
    ),
    path(
        'projects/<int:pk>',
        views.project.ProjectRepositoryList.as_view(),
        name='project_details',
    ),
    path(
        'issues/',
        views.issues.ListView.as_view(),
        name='open_issues',
    ),
    path(
        'pull_requests',
        views.pull_requests.ListView.as_view(),
        name='pull_requests_list',
    ),
    path('event-handler', views.webhook.EventHandler.as_view()),
    path('about', views.about.AboutView.as_view(), name="about"),
    path(
        'achievements',
        views.achievements.AchievementListView.as_view(),
        name='achievements',
    ),
    path(
        'contributor_achievements/<slug:slug>',
        views.contributor_achievements.ContributorAchievementListView.as_view(),
        name='contributor_achievements',
    ),
    path(
        'landing/',
        views.landing.LandingView.as_view(),
        name='landing',
    ),
    path(
        'contributor/compare_with_yourself/<slug:slug>/',
        views.contributor_compare.CompareWithYourselfView.as_view(),
        name='compare_with_yourself',
    ),
]

templates/components/flash_messages.html
{% load i18n %}

{% if messages %}
    <div class="container">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/components/footer.html
{% load i18n %}
<div class="container my-5">
  <div class="row">
    <div class="col-12 col-md">
      <ul class="list-unstyled my-0">
        <li><a target="_blank" href="http://github.com/Hexlet/hexlet-friends">{% trans "Source code" %}</a></li>
      </ul>
    </div>
    <div class="col">
      <ul class="list-unstyled my-0">
        <div class="row">
          <div class="col">
            <li><p class="h6">{% trans "Other projects" %}</p></li>
          </div>
          <div class="col">
            <li></li>
          </div>
          <div class="col">
            <li><p class="h6">{% trans "Useful resources" %}</p></li>
          </div>
          <div class="col">
            <li><a target="_blank" href="{% url 'contributors:achievements' %}">{% trans "Common statistics" %}</a></li>
          </div>
        </div>
      </ul>
      <hr>
      <ul class="list-unstyled my-0">
        <div class="row">
          <div class="col">
            <li><a target="_blank" href="{% url 'contributors:about' %}">{% trans "About project" %}</a></li>
            <li><a target="_blank" href="http://ru.hexlet.io">Hexlet</a></li>
            <li><a target="_blank" href="http://cv.hexlet.io">Hexlet CV</a></li>
            <li><a target="_blank" href="http://sicp.hexlet.io">Hexlet SICP</a></li>
          </div>
          <div class="col">
            <li><a target="_blank" href="http://hexlet-correction.herokuapp.com">Hexlet Correction</a></li>
            <li><a target="_blank" href="http://codebattle.hexlet.io">Codebattle</a></li>
            <li><a target="_blank" href="http://code-basics.com">Code Basics</a></li>
          </div>
          <div class="col">
            <li><a target="_blank" href="http://guides.hexlet.io">Hexlet Guides</a></li>
            <li><a target="_blank" href="http://ru.hexlet.io/knowledge">{% trans "Knowledge base" %}</a></li>
            <li><a target="_blank" href="http://ru.hexlet.io/pages/recommended-books">{% trans "Recommended books" %}</a></li>
            <li><a target="_blank" href="http://ru.hexlet.io/blog">{% trans "Blog" %}</a></li>
          </div>
          <div class="col">
            <li></li>
          </div>
        </div>
      </ul>
      
    </div>
  </div>
</div>

templates/components/issue_tags_list.html
{% load i18n contrib_extras %}

<div class="my-3">
    {% for label in all_contribution_labels %}
        <a href="{% url 'contributors:open_issues' %}{% get_contribution_label_query_string label|lower %}"
           class="text-decoration-none">
						<span class="badge {% if label not in contribution_labels %}bg-success{% else %}bg-secondary{% endif %}">{{ label }}</span>
        </a>
    {% endfor %}
</div>
<div>
	<a href="{% url 'contributors:open_issues' %}">
		<span class="btn btn-outline-danger">{% trans 'Reset' %}</span>
	</a>
</div>

templates/components/issues_and_pr_for_month.html
{% load i18n %}

<div class="card latest-issues-and-prs latest-for-month d-none">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link px-2 active" name="pull-requests" href="#">{% trans 'by pull requests' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-2" name="issues" href="#">{% trans 'by issues' %}</a>
        </li>
      </ul>
    </div>
    {% with tab='components/top_issues.html' %}
      {% include tab with latest_issues=latest_month_pr class='pull-requests' %}
      {% include tab with latest_issues=latest_month_issues class='issues' %}
    {% endwith %}
</div>

templates/components/navbar.html
{% load i18n static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'contributors:home' %}">{{ PROJECT_NAME }}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contributors:organizations_list' %}">
            {% trans "Organizations" %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contributors:repositories_list' %}">
            {% trans "Repositories" %}
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true"
             aria-expanded="false">
            {% trans "Leaderboard" %}
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'contributors:leaderboard_commits' %}">{% trans "Commits" %}</a>
            <a class="dropdown-item" href="{% url 'contributors:leaderboard_prs' %}">{% trans "Pull requests" %}</a>
            <a class="dropdown-item" href="{% url 'contributors:leaderboard_issues' %}">{% trans "Issues" %}</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true"
             aria-expanded="false">
            {% trans "Contributors" %}
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'contributors:contributors_for_week' %}">{% trans "For period" %}</a>
            <a class="dropdown-item" href="{% url 'contributors:contributors_list' %}">{% trans "All-time" %}</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contributors:open_issues' %}">
            {% trans "Issues" %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-nowrap" href="{% url 'contributors:pull_requests_list' %}">
            {% trans "Pull requests" %}
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto btn-group">
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true"
               aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              {% if user.is_staff %}
                <a class="dropdown-item" href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
              {% endif %}
              {% if user.contributor %}
                <a class="dropdown-item" href="{{ user.contributor.get_absolute_url }}">{% trans "My statistics" %}</a>
              {% endif %}
              {% if user.contributor %}
                <a class="dropdown-item" href="{% url 'contributors:user_settings' slug=user.contributor.login %}">{% trans "Settings" %}</a>
              {% endif %}
              <form class="dropdown-item" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">{% trans "Log out" %}</button>
              </form>
            </div>
          </li>
        {% else %}
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="{% url 'auth:github' %}">
              <img src="{% static 'images/github_icons/mark-github.svg' %}" alt="GitHub">
              {% trans "Log in" %}
            </a>
          </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav btn-group">
        <li>
          <a class="nav-link dropdown-toggle" data-bs-toggle='dropdown' role='button' aria-expanded='false'>
            <img class="mt-auto" src="{% static 'images/locale_icons/'|add:LANGUAGE_CODE|add:'.svg' %}"
                 alt="current language is {{ LANGUAGE_CODE }}" width="25">
            {{ LANGUAGE_CODE|upper }}
          </a>
          <ul class="dropdown-menu dropdown-menu-end" role='menu'>
            <li>
              <form name="setLanguage" action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                {% get_available_languages as AVAILABLE_LANGUAGES %}
                {% get_language_info_list for AVAILABLE_LANGUAGES as languages %}
                {% for language in languages %}
                  {% if language.code != LANGUAGE_CODE %}
                    <input name="language" type="hidden" value="{{ language.code|lower }}"/>
                    <a class="dropdown-item" href="javascript:document.setLanguage.submit()">
                      <img src="{% static 'images/locale_icons/'|add:language.code|add:'.svg' %}"
                           alt="set language to {{ language.code }}" width="25">
                      {{ language.name_local }}
                    </a>
                  {% endif %}
                {% endfor %}
              </form>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/components/repo_tags_list.html
{% load i18n contrib_extras %}

<div class="my-3">
    {% for label in all_labels %}
        <a href="{% url 'contributors:repositories_list' %}{% get_label_query_string label|lower %}"
           class="text-decoration-none">
            <span class="badge bg-primary {% if label not in labels %} bg-secondary {% endif %}">{{ label }}</span>
        </a>
    {% endfor %}
</div>

templates/components/search_by_name_and_state.html
{% load crispy_forms_tags %}

{% crispy form_status %}

templates/components/search_by_org.html
{% load crispy_forms_tags %}

{% crispy form_org %}

templates/components/sort_and_search_form.html
{% load crispy_forms_tags %}

{% crispy form %}

templates/components/time_note_for_issues_and_pr.html
{% load i18n %}

<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link issues-and-pr-time-note py-1 active" href="#"
       name="issues-and-pr-for-week">
      {% trans "for the past week" %}
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link issues-and-pr-time-note py-1" href="#"
       name="issues-and-pr-for-month">
      {% trans "for the past month" %}
    </a>
  </li>
</ul>

templates/components/top10_of_month.html
{% load i18n %}

<div class="card top-10-items top-month d-none">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link px-2 active" name="top-committers" href="#">{% trans 'by commits' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-2" name="top-requesters" href="#">{% trans 'by pull requests' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-2" name="top-reporters" href="#">{% trans 'by issues' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-2" name="top-commentators" href="#">{% trans 'by comments' %}</a>
        </li>
      </ul>
    </div>
    {% with top10='components/top_contributors.html' %}
      {% include top10 with contributors=top10_committers_of_month contrib_type='commits' class='top-committers'%}
      {% include top10 with contributors=top10_requesters_of_month contrib_type='pull_requests' class='top-requesters' %}
      {% include top10 with contributors=top10_reporters_of_month contrib_type='issues' class='top-reporters' %}
      {% include top10 with contributors=top10_commentators_of_month contrib_type='comments' class='top-commentators' %}
    {% endwith %}
</div>

templates/components/top_contributors.html
{% load contrib_extras %}

<ul class="list-group list-group-flush {{ class }} {% if contrib_type != 'commits' %}d-none{% endif %}">
  {% for contributor in contributors %}
    <li class="list-group-item">
      <span class="top-list-number">{{ forloop.counter }}. </span>
      <a href="{{ contributor.get_absolute_url }}">{{ contributor }}</a>
      <span class="text-muted">{% if contributor.name %} | {{ contributor.name }}{% endif %}</span>
      <span class="badge rounded-pill bg-secondary">{{ contributor|get:contrib_type }}</span>
    </li>
  {% endfor %}
</ul>

templates/components/top_issues.html
{% load i18n static %}

<ul class="list-group list-group-flush {{ class }} {% if class != 'pull-requests' %}d-none{% endif %}">
  {% for issue in latest_issues %}
    <li class="list-group-item text-truncate">
      {% if issue.type == 'iss' %}
        <img src="{% static 'images/github_icons/issue-opened.svg' %}" alt="Issue">
      {% elif issue.type == 'pr' %}
        <img src="{% static 'images/github_icons/git-pull-request.svg' %}" alt="PR">
      {% endif %}
      <a href="{{ issue.repository.get_absolute_url }}">{{ issue.repository }}</a>:
      <a href="{{ issue.html_url }}" target="_blank">{{ issue.info.title }}</a>
    </li>
  {% endfor %}
</ul>

templates/components/year_activity_chart.html
{% load static %}

<div class="mb-5"><canvas id="yearActivityChart"></canvas></div>
<script src="{% static 'js/yearActivityChart.js' %}"></script>