auth/urls.py
from django.urls import path

from auth.views import (
    GitHubAuthRedirectView,
    GitHubAuthView,
    RegistrationView,
)

app_name = 'auth'
urlpatterns = [
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('github/', GitHubAuthRedirectView.as_view(), name='github'),
    path('github/login/', GitHubAuthView.as_view(), name='github-login'),
]

config/urls.py
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from contributors.admin.custom import site
from contributors.sitemap import sitemaps
from contributors.views import robots


def trigger_error(request):
    """Trigger error for Sentry checking."""
    division_by_zero = 1 / 0  # noqa: F841


urlpatterns = [
    path('admin/', site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript_catalog'),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/', include('auth.urls')),
    path('', include('contributors.urls')),
    path('sentry-debug/', trigger_error),
    path('robots.txt', robots.RobotsTxtView.as_view(), name='robots_txt'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

contributors/urls.py
from django.urls import path

from contributors import views

app_name = 'contributors'
urlpatterns = [
    path('', views.home.HomeView.as_view(), name='home'),
    path(
        '<slug:slug>/settings/account/edit',
        views.user_settings.ChangeTokenView.as_view(),
        name='user_settings',
    ),
    path(
        'organizations/',
        views.organizations.ListView.as_view(),
        name='organizations_list',
    ),
    path(
        'organizations/<slug:slug>',
        views.organization.OrgRepositoryList.as_view(),
        name='organization_details',
    ),
    path(
        'repositories/',
        views.repositories.ListView.as_view(),
        name='repositories_list',
    ),
    path(
        'repositories/<path:slug>',
        views.repository.RepoContributorList.as_view(),
        name='repository_details',
    ),
    path(
        'leaderboard/commits',
        views.leaderboards.CommitsListView.as_view(),
        name='leaderboard_commits',
    ),
    path(
        'leaderboard/pull-requests',
        views.leaderboards.PrsListView.as_view(),
        name='leaderboard_prs',
    ),
    path(
        'leaderboard/issues',
        views.leaderboards.IssuesListView.as_view(),
        name='leaderboard_issues',
    ),
    path(
        'contributors/',
        views.contributors.ListView.as_view(),
        name='contributors_list',
    ),
    path(
        'contributors/for-month',
        views.contributors_for_period.ListView.as_view(
            extra_context={'period': 'month'},
        ),
        name='contributors_for_month',
    ),
    path(
        'contributors/for-week',
        views.contributors_for_period.ListView.as_view(
            extra_context={'period': 'week'},
        ),
        name='contributors_for_week',
    ),
    path(
        'contributors/<slug:slug>',
        views.contributor.DetailView.as_view(),
        name='contributor_details',
    ),
    path(
        'contributors/<slug:slug>/issues/',
        views.contributor_issues.ListView.as_view(),
        name='contributor_issues',
    ),
    path(
        'contributors/<slug:slug>/pullrequests/',
        views.contributor_prs.ListView.as_view(),
        name='contributor_pullrequests',
    ),
    path(
        'projects/',
        views.projects.ListView.as_view(),
        name='projects_list',
    ),
    path(
        'projects/<int:pk>',
        views.project.ProjectRepositoryList.as_view(),
        name='project_details',
    ),
    path(
        'issues/',
        views.issues.ListView.as_view(),
        name='open_issues',
    ),
    path(
        'pull_requests',
        views.pull_requests.ListView.as_view(),
        name='pull_requests_list',
    ),
    path('event-handler', views.webhook.EventHandler.as_view()),
    path('about', views.about.AboutView.as_view(), name="about"),
    path(
        'achievements',
        views.achievements.AchievementListView.as_view(),
        name='achievements',
    ),
    path(
        'contributor_achievements/<slug:slug>',
        views.contributor_achievements.ContributorAchievementListView.as_view(),
        name='contributor_achievements',
    ),
    path(
        'landing/',
        views.landing.LandingView.as_view(),
        name='landing',
    ),
    path(
        'contributor/compare_with_yourself/<slug:slug>/',
        views.contributor_compare.CompareWithYourselfView.as_view(),
        name='compare_with_yourself',
    ),
]

contributors/forms/admin_forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from requests.exceptions import HTTPError

from contributors.utils.github_lib import get_org_data


class OrgNamesForm(forms.Form):
    """A form for organization names."""

    organizations = forms.CharField(
        label=_("Organizations"),
        widget=forms.Textarea({'cols': 30, 'rows': 5}),
        help_text=_(
            "Enter organization names separated by a space or newline.",
        ),
    )

    def clean_organizations(self):
        """Check if valid names have been provided."""
        organizations = self.cleaned_data.get('organizations')
        for name in organizations.split():
            try:
                get_org_data(name)
            except HTTPError:
                raise forms.ValidationError(
                    _("Invalid name: ") + name,
                    code='invalid',
                    params={'name': name},
                )
        return organizations


class RepoNamesForm(forms.Form):
    """A form for repository names."""

    def __init__(self, *args, choices=None, **kwargs):
        """Initialize the form with a dynamic choices set."""
        super().__init__(*args, **kwargs)
        self.fields['repositories'] = forms.MultipleChoiceField(
            widget=forms.CheckboxSelectMultiple,
            choices=choices or {},
            help_text=_("Uncheck those you wish to skip."),
        )

contributors/views.py
from django.views.generic import ListView

from contributors.models import Contributor


class ContributorsListView(ListView):
    model = Contributor

contributors/views/about.py
from django.views.generic.base import TemplateView


class AboutView(TemplateView):
    """About project page view."""

    template_name = 'about.html'

contributors/views/achievements.py
from django.views import generic

from contributors.models import Contributor


class AchievementListView(generic.ListView):
    """Achievement list."""

    template_name = 'contributor/achievements_list.html'
    model = Contributor
    contributors = Contributor.objects.with_contributions()

    pull_request_ranges_for_achievements = [100, 50, 25, 10, 1]

    commit_ranges_for_achievements = [200, 100, 50, 25, 1]
    issue_ranges_for_achievements = [50, 25, 10, 5, 1]
    comment_ranges_for_achievements = [200, 100, 50, 25, 1]
    edition_ranges_for_achievements = [1000, 500, 250, 100, 1]

    def get_context_data(self, **kwargs):
        """Add context data for achievement list."""
        self.contributors_amount = Contributor.objects.count()
        context = super().get_context_data(**kwargs)
        contributors = Contributor.objects.with_contributions()

        context['contributors_amount'] = self.contributors_amount
        context['contributors_with_any_contribution'] = (
            contributors.filter(contribution_amount__gte=1).count()
        )

        # Pull request achievements:
        for pr_num in self.pull_request_ranges_for_achievements:
            context[f'contributors_pull_requests_gte_{pr_num}'] = (
                contributors.filter(pull_requests__gte=pr_num).count()
            )

        # Commit achievements:
        for commit_num in self.commit_ranges_for_achievements:
            context[f'contributors_commits_gte_{commit_num}'] = (
                contributors.filter(commits__gte=commit_num).count()
            )

        # Issue achievements:
        for issue_num in self.issue_ranges_for_achievements:
            context[f'contributors_issues_gte_{issue_num}'] = (
                contributors.filter(issues__gte=issue_num).count()
            )

        # Comment achievements:
        for comment_num in self.comment_ranges_for_achievements:
            context[f'contributors_comments_gte_{comment_num}'] = (
                contributors.filter(comments__gte=comment_num).count()
            )

        # Edition achievements:
        for ed_num in self.edition_ranges_for_achievements:
            context[f'contributors_editions_gte_{ed_num}'] = (
                contributors.filter(editions__gte=ed_num).count()
            )

        return context

contributors/views/config.py
import subprocess  # noqa: S404

import requests
from django.http import HttpResponseForbidden
from django.template.response import TemplateResponse
from django.utils.translation import gettext_lazy as _

from contributors.admin import custom
from contributors.forms import OrgNamesForm, RepoNamesForm
from contributors.models import Organization, Repository
from contributors.utils import github_lib as github
from contributors.utils import misc


def set_up_context(request):
    """Set up admin site context."""
    context = custom.site.each_context(request)
    context["title"] = _("Processing configuration")
    return context


def show_repos(request):
    """Get repositories for organizations."""
    context = set_up_context(request)
    if request.method == "POST":
        form_orgs = OrgNamesForm(request.POST)
        if form_orgs.is_valid():
            session = requests.Session()
            repos_choices = []
            for org_name in form_orgs.cleaned_data["organizations"].split():
                org_data = github.get_org_data(org_name, session)
                misc.update_or_create_record(Organization, org_data)
                repos_data = list(github.get_org_repos(org_name, session))
                for repo_data in repos_data:
                    misc.update_or_create_record(
                        Repository,
                        repo_data,
                        {"is_tracked": False, "is_visible": False},
                    )
                    repos_choices.append(
                        (repo_data["id"], repo_data["name"]),
                    )
            session.close()
            form_repos = RepoNamesForm(choices=repos_choices)
            context["form_repos"] = form_repos
    else:
        form_orgs = OrgNamesForm()

    context["form_orgs"] = form_orgs

    return TemplateResponse(request, "admin/configuration.html", context)


def collect_data(request):
    """Collect data for chosen repositories."""
    context = set_up_context(request)
    if request.method == "POST":
        repo_ids = request.POST.getlist("repositories")
        repos = Repository.objects.filter(id__in=repo_ids)
        for repo in repos:
            repo.is_tracked = True
            repo.is_visible = True
        Repository.objects.bulk_update(repos, ["is_tracked", "is_visible"])
        fetch_command = ["./manage.py", "fetchdata", "--repo"]
        fetch_command.extend([repo.full_name for repo in repos])  # noqa: E501
        subprocess.Popen(fetch_command)  # noqa: S603
        return TemplateResponse(request, "admin/data_collection.html", context)
    return HttpResponseForbidden("Forbidden.")

contributors/views/contributor.py
from django.db.models import Count, F, Q, Sum  # noqa: WPS347
from django.db.models.functions import Coalesce
from django.views import generic

from contributors.models import Contribution, Contributor, Repository
from contributors.views.mixins import (
    ContributorsJsonMixin,
    ContributorTotalStatMixin,
)


class DetailView(
    ContributorTotalStatMixin, ContributorsJsonMixin, generic.DetailView,
):
    """Contributor's details."""

    model = Contributor
    template_name = 'contributor/contributor_details.html'
    slug_field = 'login'

    def get_context_data(self, **kwargs):
        """Add additional context for the contributor."""
        context = super().get_context_data(**kwargs)

        repositories = Repository.objects.select_related(
            'organization',
        ).filter(
            is_visible=True,
            contribution__contributor=self.object,
        ).annotate(
            commits=Count('id', filter=Q(contribution__type='cit')),
            additions=Coalesce(Sum('contribution__stats__additions'), 0),
            deletions=Coalesce(Sum('contribution__stats__deletions'), 0),
            pull_requests=Count(
                'contribution', filter=Q(contribution__type='pr'),
            ),
            issues=Count('contribution', filter=Q(contribution__type='iss')),
            comments=Count('contribution', filter=Q(contribution__type='cnt')),
        ).order_by('organization', 'name')

        context['repositories'] = repositories
        context['contributions_for_year'] = (
            self.object.contribution_set.for_year()
        )
        context['top_repository'] = repositories.annotate(
            summary=F('commits') + F('pull_requests') + F('issues') + F('comments'),  # noqa: WPS221, E501
        ).order_by('-summary').first()

        context['summary'] = Contribution.objects.filter(
            contributor=self.object,
        ).aggregate(
            commits=Count('id', filter=Q(type='cit')),
            pull_requests=Count('id', filter=Q(type='pr')),
            issues=Count('id', filter=Q(type='iss')),
            comments=Count('id', filter=Q(type='cnt')),
        )

        contributors = Contributor.objects.visible()
        contributors_ordered = contributors.order_by('name')
        context['contributors'] = contributors_ordered.values('id', 'name')

        context['current_contributor'] = self.object
        if self.request.GET.get('compare') == 'yes':
            current_user = self.request.user.contributor
            context['my_contributions_for_year'] = (
                current_user.contribution_set.for_year()
            )

        return context

contributors/views/contributor_compare.py
from django.db.models import Count, Q
from django.views.generic import ListView

from contributors.models import Contribution, Contributor, Repository
from contributors.views.filters import DetailTablePeriodFilter


class CompareWithYourselfView(ListView):
    """View of comparing current user with another one."""

    model = Contribution
    template_name = ('contributors_sections/'
                     'contributors/contributor_compare_with_yourself.html')
    slug_field = 'contributor'

    def get_queryset(self):
        """Override method for good queryset."""
        qs_enemy = Contribution.objects.filter(
            contributor=Contributor.objects.filter(
                login=self.request.path.split('/')[-2],
            ).first(),
        )
        qs_me = Contribution.objects.filter(
            contributor=Contributor.objects.get(login=self.request.user),
        )
        return qs_enemy | qs_me

    def get_context_data(self, **kwargs):
        """Adding filter and data to context data."""
        context = super().get_context_data(**kwargs)
        context['enemy_obj'] = Contributor.objects.filter(
            login=self.request.path.split('/')[-2],
        ).first()
        context['filter'] = DetailTablePeriodFilter(
            self.request.GET,
            queryset=self.get_queryset(),
        )

        me_qs = context['filter'].qs.filter(
            contributor=Contributor.objects.get(login=self.request.user),
        )
        context['me'] = me_qs.aggregate(
            commits=Count('id', filter=Q(type='cit')),
            pull_requests=Count('id', filter=Q(type='pr')),
            issues=Count('id', filter=Q(type='iss')),
            comments=Count('id', filter=Q(type='cnt')),
        )
        me_top_repo_with_counter = me_qs.values('repository').annotate(
            count=Count('repository'),
        ).order_by('-count').first()
        if me_top_repo_with_counter:
            me_top_repo_pk = me_top_repo_with_counter['repository']
            me_repo_full_name = Repository.objects.filter(
                pk=me_top_repo_pk,
            ).first().full_name
            context['me_top_repo'] = me_repo_full_name
        else:
            context['me_top_repo'] = '---'

        enemy_qs = context['filter'].qs.filter(
            contributor=context['enemy_obj'].pk,
        )
        context['enemy'] = enemy_qs.aggregate(
            commits=Count('id', filter=Q(type='cit')),
            pull_requests=Count('id', filter=Q(type='pr')),
            issues=Count('id', filter=Q(type='iss')),
            comments=Count('id', filter=Q(type='cnt')),
        )
        enemy_top_repo_with_counter = enemy_qs.values('repository').annotate(
            count=Count('repository'),
        ).order_by('-count').first()
        if enemy_top_repo_with_counter:
            enemy_top_repo_pk = enemy_top_repo_with_counter['repository']
            enemy_repo_full_name = Repository.objects.filter(
                pk=enemy_top_repo_pk,
            ).first().full_name
            context['enemy_top_repo'] = enemy_repo_full_name
        else:
            context['enemy_top_repo'] = '---'
        return context

templates/contributors_sections/contributors/contributor_compare_with_yourself.html
{% extends 'base.html' %}
{% load i18n static %}
{% load mathfilters %}
{% block head_scripts %}
{% include 'components/activity_chart/scripts.html' %}
{% endblock head_scripts %}
{% block title %}{% trans "Compare" %}: {{ user }} - {{ enemy_obj.login }}{% endblock %}

{% block content %}
<h3>
    {% trans "Statistics Compare" %}
</h3>
<ul class="nav nav-tabs">
    <li class="nav-item">
        {% if not request.GET.period  or request.GET.period == '' %}
        <a class="nav-link active" href="?period=#">{% trans "for all time" %}</a>
        {% else %}
        <a class="nav-link" href="?period=#">{% trans "for all time" %}</a>
        {% endif %}
    </li>
    <li class="nav-item">
        {% if request.GET.period == 'for_year' %}
        <a class="nav-link active" href="?period=for_year">{% trans "for year" %}</a>
        {% else %}
        <a class="nav-link" href="?period=for_year">{% trans "for year" %}</a>
        {% endif %}
    </li>
    <li class="nav-item">
        {% if request.GET.period == 'for_month' %}
        <a class="nav-link active" href="?period=for_month">{% trans "for month" %}</a>
        {% else %}
        <a class="nav-link" href="?period=for_month">{% trans "for month" %}</a>
        {% endif %}
    </li>
    <li class="nav-item">
        {% if request.GET.period == 'for_week' %}
        <a class="nav-link active" aria-current="page" href="?period=for_week">{% trans "for week" %}</a>
        {% else %}
        <a class="nav-link" aria-current="page" href="?period=for_week">{% trans "for week" %}</a>
        {% endif %}
    </li> 
</ul>


<div class="container d-flex justify-content-center">
<div class="text-center text-dark" style="width: 75%;">
    <div class="row py-2">
        <div class="col h3 mb-0"></div>
        <div class="col h3 fw-bold mb-0 text-body-secondary">
            <a class="text-decoration-none" href="{% url 'contributors:contributor_details' slug=user %}">{{ user }}</a>
        </div>
        <div class="col h3 fw-bold mb-0 text-body-secondary">
            <a class="text-decoration-none" href="{% url 'contributors:contributor_details' slug=enemy_obj.login %}">{{ enemy_obj.login }}</a>
        </div>
    </div>
    <div class="row py-2">
        <div class="col h5 mb-0 text-end">
            <span class="text-decoration-none">{% trans "Top repo" %}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span>{{ me_top_repo }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span>{{ enemy_top_repo }}</span>
        </div>
    </div>
    <div class="row py-2">
        <div class="col h5 mb-0 text-end">
            <span class="text-decoration-none">{% trans "commits" %}</span>
        </div>
        {% with diff=me.commits|sub:enemy.commits %}
        {% if diff > 0 %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-success">{{ me.commits }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-danger">{{ enemy.commits }}</span>
        </div>
        {% elif diff < 0 %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-danger">{{ me.commits }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-success">{{ enemy.commits }}</span>
        </div>
        {% else %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-muted">{{ me.commits }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-muted">{{ enemy.commits }}</span>
        </div>
        {% endif %}
        {% endwith %}
    </div>
    <div class="row py-2">
        <div class="col h5 mb-0 text-end">
            <span class="text-decoration-none">{% trans "pull-requests" %}</span>
        </div>
        {% with diff=me.pull_requests|sub:enemy.pull_requests %}
        {% if diff > 0 %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-success">{{ me.pull_requests }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-danger">{{ enemy.pull_requests }}</span>
        </div>
        {% elif diff < 0 %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-danger">{{ me.pull_requests }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-success">{{ enemy.pull_requests }}</span>
        </div>
        {% else %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-muted">{{ me.pull_requests }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-muted">{{ enemy.pull_requests }}</span>
        </div>
        {% endif %}
        {% endwith %}
    </div>
    <div class="row py-2">
        <div class="col h5 mb-0 text-end">
            <span class="text-decoration-none">{% trans "issues" %}</span>
        </div>
        {% with diff=me.issues|sub:enemy.issues %}
        {% if diff > 0 %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-success">{{ me.issues }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-danger">{{ enemy.issues }}</span>
        </div>
        {% elif diff < 0 %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-danger">{{ me.issues }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-success">{{ enemy.issues }}</span>
        </div>
        {% else %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-muted">{{ me.issues }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-muted">{{ enemy.issues }}</span>
        </div>
        {% endif %}
        {% endwith %}
    </div>
    <div class="row py-2">
        <div class="col h5 mb-0 text-end">
            <span class="text-decoration-none">{% trans "comments" %}</span>
        </div>
        {% with diff=me.comments|sub:enemy.comments %}
        {% if diff > 0 %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-success">{{ me.comments }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-danger">{{ enemy.comments }}</span>
        </div>
        {% elif diff < 0 %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-danger">{{ me.comments }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-success">{{ enemy.comments }}</span>
        </div>
        {% else %}
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-muted">{{ me.comments }}</span>
        </div>
        <div class="col h5 mb-0 text-body-secondary">
            <span class="text-muted">{{ enemy.comments }}</span>
        </div>
        {% endif %}
        {% endwith %}
    </div>
</div>
</div>

{% endblock %}

templates/contributors_sections/contributors/contributors_for_period.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {% if is_week %}
        {% trans "Contributors for week" %}
    {% else %}
        {% trans "Contributors for month" %}
    {% endif %}
{% endblock %}

<!-- Open Graph tags -->
{% block og_title %}
    {% if is_week %}
        {% trans "Contributors for week" %}
    {% else %}
        {% trans "Contributors for month" %}
    {% endif %}
{% endblock og_title %}
<!-- End Open Graph tags -->

{% block header %}
    {% if is_week %}
        {% trans "Contributors for week" %}
    {% else %}
        {% trans "Contributors for month" %}
    {% endif %}
{% endblock %}

{% block additional %}
  {% include 'components/time_note.html' %}
{% endblock %}
{% block content %}
  {% include 'components/search_by_org_and_contributors.html' %}
  {% include 'components/tables/contributors_list.html' %}
  {% include 'components/pagination.html' %}
{% endblock content %}

templates/contributors_sections/contributors/contributors_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Contributors" %}{% endblock %}
<!-- Open Graph tags -->

{% block og_title %}{% trans "Contributors" %}{% endblock og_title %}
<!-- End Open Graph tags -->
{% block header %}{% trans "Contributors" %}{% endblock %}
{% block content %}
  {% include 'components/search_by_org_and_contributors.html' %}
  {% include 'components/tables/contributors_list.html' %}
  {% include 'components/pagination.html' %}
{% endblock content %}